### 
@url = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6InJpdWtpc3RldmVAZ21haWwuY29tIiwiaWF0IjoxNzQ5MDY0MjY4LCJleHAiOjE3NDkwNjYwNjh9.6SGhdsndM0JaICcamFiX0-88-LX9XxCBmEbfXGblHss
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6InJpdWtpc3RldmVAZ21haWwuY29tIiwiaWF0IjoxNzQ5MDY0MjY4LCJleHAiOjE3NDk2NjkwNjh9.UXBaNCOpPbhZlXuL8mt3vijoGLNGLWEV3rWMmFQSJdg
### Cache Metrics
GET {{url}}/cache-metrics

### Cache Management
POST {{url}}/cache
Content-Type: application/json

{
  "key": "user_123",
  "value": "John Doe Profile Data",
  "ttl": 3600
}
### login a new user 
POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "riukisteve@gmail.com",
  "password": "securepassword"
}

### Logout
POST {{url}}/auth/signout/12
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": 12
}

### Refresh Tokens
POST {{url}}/auth/refresh/12
Authorization: Bearer {{refreshToken}}
Content-Type: application/json

{
  "userId": 12,
  "refreshToken": "{{refreshToken}}"
}

###
POST {{url}}/auth/signup
Content-Type: application/json

{
  "first_name": "Kimberly",
  "last_name": "Njeri",
  "email": "kimjay@gmail.com",
  "password": "securepassword",
  "role": "Sales"
}

###
POST {{url}}/seed

/// Product routes
###
GET {{url}}/products/all/
###
GET {{url}}/products/6/

###
POST {{url}}/products/create
Content-Type: application/json

{
  "product_id": 11,
  "name": "Wireless Mouse",
  "description": "Ergonomic wireless mouse with USB receiver",
  "sku": "10001",
  "price": 29.99,
  "category_id": 1,
  "supplier_id": 5,
  "created_at": "2024-01-10T09:00:00.000Z",
  "updated_at": "2024-01-10T09:00:00.000Z"
}

###
PATCH {{url}}/products/update/81
Content-Type: application/json

{
  "name": "Updated Product Name",
  "description": "Updated product description.",
  "price": 19.99
}

###
DELETE {{url}}/products/delete/5

/// User routes
###
GET {{url}}/users/all
###
GET {{url}}/users/1

###
POST {{url}}/users/create
Content-Type: application/json

{
  "first_name": "Mwaniki",
  "last_name": "Tiffany",
  "email": "mwanikitiffany@gmail.com",
  "password": "securepassword",
  "role": "Admin"
}

###
PATCH {{url}}/users/update/3
Content-Type: application/json

{
  "first_name": "Updated First Name",
  "last_name": "Updated Last Name",
  "email": "updated.email@example.com",
  "role": "Manager"
}

###
DELETE {{url}}/users/delete/5

/// Category routes
###
GET {{url}}/categories/all
###
GET {{url}}/categories/9

###
POST {{url}}/categories/create
Content-Type: application/json

{
  "name": "Electronics",
  "description": "Electronic gadgets and devices"
}

###
PATCH {{url}}/categories/update/6
Content-Type: application/json

{
  "name": "Updated Category Name",
  "description": "Updated category description"
}

###
DELETE {{url}}/categories/delete/1

// end here


/// Supplier routes
###
GET {{url}}/suppliers/
###
GET {{url}}/suppliers/16

###
POST {{url}}/suppliers/
Content-Type: application/json

{
  "name": "Tech Supplies Ltd.",
  "contact_info": "+1234567890"
}

// retest
###
PATCH {{url}}/suppliers/21
Content-Type: application/json

{
  "name": "Updated Supplier Name",
  "contact_info": "updated@techsupplies.com"
}

###
DELETE {{url}}/suppliers/21

/// Warehouse routes
###
GET {{url}}/warehouses/all
###
GET {{url}}/warehouses/11

###
POST {{url}}/warehouses/create
Content-Type: application/json

{
  "name": "Main Warehouse",
  "location": "Nairobi, Kenya"
}

###
PATCH {{url}}/warehouses/update/11
Content-Type: application/json

{
  "name": "Updated Warehouse Name",
  "location": "Updated Location"
}

###
DELETE {{url}}/warehouses/delete/11

/// Order routes (with relationships)
###
GET {{url}}/orders/all
###
GET {{url}}/orders/21

###
POST {{url}}/orders/create
Content-Type: application/json

{
  "user_id": 1,
  "products": [1, 2],
  "total_price": 59.98,
  "status": "Completed"
}

###
PATCH {{url}}/orders/update/21
Content-Type: application/json

{
  "status": "Completed"
}

###
DELETE {{url}}/orders/delete/1

/// Inventory routes (with relationships)
###
GET {{url}}/inventories/all
###
GET {{url}}/inventories/41

###
POST {{url}}/inventories/create
Content-Type: application/json

{
  "product_id": 1,
  "warehouse_id": 1,
  "stock_qty": 100
}

###
PATCH {{url}}/inventories/update/41
Content-Type: application/json

{
  "stock_qty": 150
}

###
DELETE {{url}}/inventories/delete/41

/// Return routes (with relationships)
###
GET {{url}}/returns/all
###
GET {{url}}/returns/11

###
POST {{url}}/returns/create
Content-Type: application/json

{
  "order_id": 11,
  "product_id": 1,
  "quantity": 1,
  "return_reason": "Defective item",
  "createdAt": "2024-01-15T09:00:00.000Z"
}

###
PATCH {{url}}/returns/update/11
Content-Type: application/json

{
  "return_reason": "Changed mind"
}

###
DELETE {{url}}/returns/delete/11

/// Pricing routes (with relationships)
###
GET {{url}}/pricings/all
###
GET {{url}}/pricings/21

// check
###
POST {{url}}/pricings/create
Content-Type: application/json

{
  "product_id": 1,
  "discount": 25.99,
  "promotion": "New Year Sale",
  "start_date": "2024-01-10",
  "end_date": "2024-01-20"
}

###
PATCH {{url}}/pricings/update/21
Content-Type: application/json

{
  "discount": 22.99
}

###
DELETE {{url}}/pricings/delete/1

/// Transaction routes (with relationships)
###
GET {{url}}/transactions/all
###
GET {{url}}/transactions/12

###
POST {{url}}/transactions/create
Content-Type: application/json

{
  "product_id": 21,
  "quantity": 2,
  "price": 59.98,
  "type": "Sale"
}

###
PATCH {{url}}/transactions/update/12
Content-Type: application/json

{
  "price": 60.00
}

###
DELETE {{url}}/transactions/delete/1