###
@url = http://localhost:8000

###
POST {{url}}/seed


/// Product routes Worked 😎😎😎
###
GET {{url}}/products/all/
###
GET {{url}}/products/1/

###
POST {{url}}/products/create
Content-Type: application/json

{
  "product_id": 11,
  "name": "Wireless Mouse",
  "description": "Ergonomic wireless mouse with USB receiver",
  "sku": 10001,
  "price": 29.99,
  "category_id": 1,
  "supplier_id": 5,
  "created_at": "2024-01-10T09:00:00.000Z",
  "updated_at": "2024-01-10T09:00:00.000Z"
}

###
PATCH {{url}}/products/update-product/3
Content-Type: application/json

{
  "id": 3,
  "name": "Updated Product Name",
  "description": "Updated product description.",
  "price": 19.99
}

###
DELETE {{url}}/products/delete/5

// user routes
###
GET {{url}}/users/all
###
GET {{url}}/users/1

###
POST {{url}}/users/create
Content-Type: application/json

{
  "first_name": "Mwaniki",
  "last_name": "Tiffany",
  "email": "mwanikitiffany@gmail.com",
  "password": "securepassword",
  "role": "Admin"
}

###
PATCH {{url}}/users/update/3
Content-Type: application/json

{
  "first_name": "Updated First Name",
  "last_name": "Updated Last Name",
  "email": "updated.email@example.com",
  "role": "Manager"
}

###
DELETE {{url}}/users/delete/5