# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - redeployedinventory

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

  # Remove node_modules so it does not get zipped/deployed
      - name: Cleanup node_modules before packaging
        run: rm -rf node_modules

      # Zip everything except node_modules, .git, test, coverage, etc.
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip dist/ package.json package-lock.json . -x "node_modules/*" -x ".git/*" -x "test/*" -x "coverage/*" -x "*.log"

      - name: Validate artifact contents
        run: unzip -l release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B8DB16489687400AB8E195C963CE79EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FF928999DC384ADA97A2E7094E43CD5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B87EEEA1C06A4B83BC9C3D1522BC7763 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'redeployedinventory'
          slot-name: 'Production'
          package: .
          
